export { default as Home } from './home/home';
export { default as AppError } from './app-error/app-error';
export { default as AppLoading } from './app-loading/app-loading';
export { default as Friend } from './friend-page/friend-page';
export { default as FriendGoal } from './friend-goal/friend-goal';
export { default as FriendItem } from './friend-item/friend-item';
export { default as FriendItems } from './friend-items/friend-items';
export { default as FriendContent } from './friend-content/friend-content';
// export { default as FriendCreationComponent } from './friend-creation/friend-creation-component';
export { default as Header } from './header/header';
export { default as Modal } from './modal/modal';
export { default as NavMenu } from './nav-menu/nav-menu';
export { default as ModalContent } from './modal-content/modal-content';
export { default as Registration } from './authorization/registration';
export { default as Login } from './authorization/login';
export { default as Settings } from './settings/settings';
